### ISSUE TITLE
502 when trying to create new project

### ISSUE THREAD

**Issue by pdehaan** [mozilla/servicebook#33]
http://servicebook.dev.mozaws.net/project/ is giving me the following hard error:

```
502 Bad Gateway

nginx/1.10.0 (Ubuntu)
```

I need to add about 3 more projects I'm working on.

**Comment by tarekziade** [comment]
Thanks for letting me know,looks like a regression from the ajax feature

**Comment by pdehaan** [comment]
I created 4 new projects this morning. Closing as fixed.
