### ISSUE TITLE
Search appears to be broken

### ISSUE THREAD

**Issue by karlht** [mozilla/servicebook#39]
Steps to reproduce:

1. Go to http://servicebook.dev.mozaws.net/
2. Enter "Karl" (no quotes) in the search bar.

Expected results:
All of my projects.

Actual results:
No results.

**Comment by karlht** [comment]
Can confirm that this is fixed in dev.

However, the stage instance at https://servicebook.stage.mozaws.net/ appears to have the same problem now.

**Comment by tarekziade** [comment]
we're not done deploying it yet

**Comment by karlht** [comment]
Search is now working on both dev and stage.
