### ISSUE TITLE
Makefile is clobbering version.json

### ISSUE THREAD

**Issue by ckolos** [mozilla/servicebook#40]
This code:
https://github.com/mozilla/servicebook/blob/master/circle.yml#L12-L18

creates a version.json that contains the following:

```
{
"commit": "7749f0a4d0d50c5ab3cf03b62e05f17004f68992",
"version":	"",
"source":	"https://github.com/mozilla/servicebook",
"build":	"https://circleci.com/gh/mozilla/servicebook/27"
}
```

However 

https://github.com/mozilla/servicebook/blob/7749f0a4d0d50c5ab3cf03b62e05f17004f68992/Makefile#L35  creates a version.json with the following information:

```
{"source": "https://github.com/mozilla/servicebook", "commit": "7749f0a", "version": "1.0"}
```

and clobbering the version.json created in the circle.yml manifest.

As a result, the version.json in the finished image is missing the build_url which is a critical piece of information required for the container verification process to complete.

It looks to me like the file created in the Makefile is contains information redundant to that provided by circle, modulo the version/Tag information; suggest removing the Makefile version.

**Comment by ckolos** [comment]
Actually, this is probably happening in the Dockerfile here:

https://github.com/mozilla/servicebook/blob/master/Dockerfile#L18

So I don't actually know the Makefile is the problem at all

**Comment by tarekziade** [comment]
Oops that's some leftovers from the previous version. We can remove them from both places. I see you've started a branch, so I'll let you push it. Thanks
