### ISSUE TITLE
[stage] Editing a project's description results in an HTTP 500

### ISSUE THREAD

**Issue by karlht** [mozilla/servicebook#43]
There should be a traceback in the logs at around 2017-08-29 21:50 UTC.

URL requested was https://servicebook.stage.mozaws.net/project/5/edit

**Comment by tarekziade** [comment]
Thanks. @ckolos are you able to get us the logs?

**Comment by ckolos** [comment]
There are no stack traces from that time in the docker logs for the api or ui instances. I'll send the journal from that time via email.

**Comment by tarekziade** [comment]
Looks like the 500 TB is not emited in the right stream. I will add sentry support so we can find out what happens

**Comment by davehunt** [comment]
This is no longer an issue.
