### ISSUE TITLE
3 /ui-icons images are missing/404s when editing a project's test URLs

### ISSUE THREAD

**Issue by stephendonner** [mozilla/servicebook#48]
When editing a project's tests-repo URL (unit, functional, etc.), the resulting dialog is missing a few image assets:

https://servicebook.stage.mozaws.net/static/images/ui-icons_777777_256x240.png
https://servicebook.stage.mozaws.net/static/images/ui-icons_444444_256x240.png
https://servicebook.stage.mozaws.net/static/images/ui-icons_555555_256x240.png

<img width="1752" alt="screen shot 2017-09-19 at 3 14 56 pm" src="https://user-images.githubusercontent.com/387249/30618033-99eba16e-9d4d-11e7-8983-290c8a56e2c5.png">

**Comment by davehunt** [comment]
:heart: the recent search in the screenshot @stephendonner. I believe this should be raised in servicebook-web, and as I have the project open I'll take a quick look into this.

**Comment by davehunt** [comment]
I've raised this over on servicebook-web and opened a pull request.
